
export const FETCH_PASSWORD_REQUEST = "FETCH_PASSWORD_REQUEST";
export const FETCH_PASSWORD_SUCCESS = "FETCH_PASSWORD_SUCCESS";
export const FETCH_PASSWORD_FAILURE = "FETCH_PASSWORD_FAILURE";

export const SAVE_PASSWORD_DATA = "SAVE_PASSWORD_DATA";
