
export const FETCH_REGISTER_REQUEST = "FETCH_REGISTER_REQUEST";
export const FETCH_REGISTER_SUCCESS = "FETCH_REGISTER_SUCCESS";
export const FETCH_REGISTER_FAILURE = "FETCH_REGISTER_FAILURE";

export const SAVE_REGISTER_DATA = "SAVE_REGISTER_DATA";

export const LOGOUT = "LOGOUT";


