export const FETCH_QUIZ_REQUEST = "FETCH_QUIZ_REQUEST";
export const FETCH_QUIZ_SUCCESS = "FETCH_QUIZ_SUCCESS";
export const FETCH_QUIZ_FAILURE = "FETCH_QUIZ_FAILURE";

export const FETCH_QUIZ_ANSWER_REQUEST = "FETCH_QUIZ__ANSWER_REQUEST";
export const FETCH_QUIZ__ANSWER_SUCCESS = "FETCH_QUIZ__ANSWER_SUCCESS";
export const FETCH_QUIZ__ANSWER_FAILURE = "FETCH_QUIZ__ANSWER_FAILURE";
export const REMOVE_QUIZ_QUESTIONS = "REMOVE_QUIZ_QUESTIONS";
export const REMOVE_QUIZ_ANSWERS = "REMOVE_QUIZ_ANSWERS";
