export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";


//fetch lesson module data
export const FETCH_LESSON_REQUEST = "FETCH_LESSON_REQUEST";
export const FETCH_LESSON_SUCCESS = "FETCH_LESSON_SUCCESS";
export const FETCH_LESSON_FAILURE = "FETCH_LESSON_FAILURE";

export const SAVE_LESSON_DATA = "SAVE_LESSON_DATA";

export const SEARCH_DATA = "SEARCH_DATA";
