export const OPEN_SAVE_MODAL = "OPEN_SAVE_MODAL";
export const CLOSE_SAVE__MODAL = "CLOSE_SAVE__MODAL";

export const OPEN_DELETE_MODAL = "OPEN_DELETE_MODAL";
export const CLOSE_DELETE__MODAL = "CLOSE_DELETE__MODAL";

export const OPEN_PASSWORD_MODAL = "OPEN_PASSWORD_MODAL";
export const CLOSE_PASSWORD_MODAL = "CLOSE_PASSWORD_MODAL";
