export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";

export const START_BUTTON_LOADING = "START_BUTTON_LOADING";
export const STOP_BUTTON_LOADING = "STOP_BUTTON_LOADING";


export const START_SUBMIT_BUTTON_LOADING = "START_SUBMIT_BUTTON_LOADING";
export const STOP_SUBMIT_BUTTON_LOADING = "STOP_SUBMIT_BUTTON_LOADING";

